export const CATEGORIES_ACTION_TYPE = {
    SET_CATEGORIES: "CATEGOIRES/SET_CATEGORIES",
    FETCH_CATEGOIRES_START: "CATEGOIRES/FETCH_CATEGOIRES_START",
    FETCH_CATEGOIRES_SUCCESS: "CATEGOIRES/FETCH_CATEGOIRES_SUCCESS",
    FETCH_CATEGOIRES_FAILED: "CATEGOIRES/FETCH_CATEGOIRES_FAILED"
}